[plugin]
repository = "https://github.com/Lerofni/TooltipNotes.git"
commit = "fd5c937716bd6224056232d06cfb7680f055e2d9"
owners = ["Lerofni"]
project_path = "TooltipNotes"
changelog = """
1.3.0.1

Bugfix for loading/saving notes

"""
